app:
  cp:
#    for JCSP
    keystore: HDIMAGE

#    for JCP
#    keystore: HDImageStore

    alias: test2012
    pin: ""
  controller:
    encrypt: "/encr"
    decrypt: "/decr"
    sign: "/sign"
    verify: "/verify"
    tls: "/tls"
    cert: "/cert"
    raw-sign: "/raw/sign"
    raw-verify: "/raw/verify"
server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
