app:
  cp:
    providername: JCSP
#    for JCSP
    keystorename: HDIMAGE

#    for JCP
#    keystorename: HDImageStore

    alias: test2012
    pin: ""
    crl-folder: "crls"
  controller:
    encrypt: "/encr"
    decrypt: "/decr"
    sign: "/sign"
    verify: "/verify"
    tls: "/tls"
    cert: "/cert"
    raw-sign: "/raw/sign"
    raw-verify: "/raw/verify"
server:
  port: 8080
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      file-size-threshold: 60MB
