app:
  cp:
    keystore: HDIMAGE
    alias: test2012
    pin: ""
  controller:
    encrypt: "/encr"
    sign: "/sign"
    verify: "/verify"
    tls: "/tls"
server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB